heat_template_version: 2013-05-23
description: >
  A Heat template which deployed a highly available scaling group with a single load balancer.
  Ver. 1.0.5-0
parameters:
  nameprefix:
    type: string
    description: A prefix string for the name of the instance
  instance_name:
    type: string
    description: Instance name - can be the component name
  key_name:
    type: string
    description: Name of an existing key pair to use for the instance
  flavor:
    type: string
    description: flavor for the instance to be created
  image:
    type: string
    description: Name of the image to use for the instance
  availability_zone:
    type: string 
    description: The Availability Zone in which to launch the instance.
  security_group_id: 
    type: string 
    description: ID of an admin security group.
  private_network_id:
    type: string
    description: ID of network into which servers get deployed 
  private_subnet_id:
    type: string
    description: ID of network subnet into which servers get deployed
  
  min_size:
    type: number
    description: The minimum size of the scaling group
  max_size:
    type: number
    description: The maximum size of the scaling group 
  
  lb_name:
    type: string
    description: The LB Name. will be in <nameprefix>-<instance-name>-<lb-name>  
  port:
    type: string
    description: The listening port. 
  lb_protocol:
    type: string
    description: Load Balancer protocol.
    constraints:
      - allowed_values: [ HTTP, HTTPS, TCP ]
        description: Value must be one of 'HTTP' , 'HTTPS' or 'TCP'
  environment:
    type: string
    description: DNS environment name  
  component_installation:
    type: string
    description: The boot script to run on instance creation.
  deployment_timeout:
    type: number
    description: The time it takes for this instance to be fully deployed.
      
resources:

  monitor:
    type: OS::Neutron::HealthMonitor
    properties:
      type: TCP
      delay: 5
      max_retries: 5
      timeout: 5
  
  
  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Security Group for Scaling Group
      rules:
        - remote_ip_prefix: 
            str_replace:
              template:
                lb_vip/32
              params:
                lb_vip: { get_attr: [pool , vip , address] }    
          protocol: tcp
          port_range_min: { get_param: port }
          port_range_max: { get_param: port }
 
  pool:
    type: OS::Neutron::Pool
    properties:
      name:
        str_replace:
          template: $nameprefix-$instance_name-$lb_name
          params:
            $nameprefix : { get_param: nameprefix }
            $instance_name : { get_param: instance_name }
            $lb_name: { get_param: lb_name }
      protocol: { get_param: lb_protocol }
      monitors: [{get_resource: monitor}]
      subnet_id: {get_param: private_subnet_id}
      lb_method: ROUND_ROBIN
      vip:
        name: { get_param: lb_name } 
        protocol_port: { get_param: port }       
  lb:
    type: OS::Neutron::LoadBalancer
    properties:
      protocol_port: 80
      pool_id: {get_resource: pool}   
  
  group:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      min_size: { get_param: min_size }
      max_size: { get_param: max_size }  
      desired_capacity: { get_param: min_size }  
      resource:
        type: __scaling_group_instance_for_one_lb.yaml
        properties:
          nameprefix: { get_param: nameprefix }
          instance_name: { get_param: instance_name }
          image: {get_param: image}
          key_name: {get_param: key_name}
          flavor: {get_param: flavor}
          groupname_stack: { get_param: "OS::stack_name" }
          private_network_id: {get_param: private_network_id}
          security_groups_ids:
            - {get_param: security_group_id }
            - {get_resource: security_group } 
          availability_zone: { get_param: availability_zone }
          lb_details: { "name" : { get_attr: [ pool, name ] }, "pool_id": {get_resource: pool}, "port": { get_param: port }, "internal_ip": { get_attr: [ pool, vip, address ] } }
          environment: { get_param: environment }
          component_installation: { get_param: component_installation }
          deployment_timeout: { get_param : deployment_timeout }
          
          
  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: group}
      cooldown: 60
      scaling_adjustment: 1
  scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: group}
      cooldown: 60
      scaling_adjustment: -1
  
outputs:
  lb_internal_ip:
    description: Load balancer IP 
    value: { get_attr: [ pool, vip, address ] }
  lb_fqdn:
    description: Load balancer FQDN 
    value: { get_attr: [ pool, name ] }
  scaleup_url:
    description: alarm url for scale up
    value: { get_attr: [ scaleup_policy, alarm_url ] }
  scaledown_url:
    description: alarm url for scale up
    value: { get_attr: [ scaledown_policy, alarm_url ] } 